name: ${pluginName}
version: ${version}
main: net.refractored.spearicalutils.SpearicalPlugin
api-version: "1.21"
authors: [ refractored ]
dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

  - name: WorldGaurd
    required: true
    bootstrap: false

  - name: FastAsyncWorldEdit
    required: true
    bootstrap: false

  - name: PlayerPoints
    required: true
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false
